"""Renders downloader shell script from a file list/table.

Reads FITS filenames from positional args or stdin.
Input may be a plain list or a table; in table mode only the first column
is used. The resulting script is written to stdout.

The downloader script is generated by `ocafitsfiles.render_download_script`.

v. 1.0.0
"""

import argparse
import logging
import signal
import sys
from argparse import ArgumentParser

from ocafitsfiles import render_download_script

log = logging.getLogger("collectdownloader")


def main() -> int:
    argparser = ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    argparser.add_argument(
        "files",
        nargs="*",
        help="Input rows (if omitted, read from stdin)",
    )
    argparser.add_argument(
        "-u",
        "--user",
        required=True,
        help="OCADB username embedded in generated downloader script",
    )
    argparser.add_argument("-v", "--verbose", action="count", default=0)

    argparser.epilog = """
examples:

    fitscollect -n -o ngc300 | fitscollectdownloader -u mkopernik > download.sh
    fitscollectparquet -n --sciprog FT2025B-1 | fitscollectdownloader -u mkopernik > download.sh
    fitscollectlist file1.fits file2.fits | fitscollectdownloader -u mkopernik > download.sh
    fitscollectdownloader -u mkopernik zb08c_1075_66218.fits zb08c_1075_66218_zdf.fits > download.sh
"""

    args = argparser.parse_args()

    try:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except (AttributeError, ValueError):
        pass

    log_format = "%(asctime)s [%(levelname)s] [%(name)s] %(message)s"
    if args.verbose == 1:
        logging.basicConfig(level=logging.INFO, format=log_format)
    elif args.verbose > 1:
        logging.basicConfig(level=logging.DEBUG, format=log_format)
    else:
        logging.basicConfig(level=logging.WARNING, format=log_format)

    if args.files:
        data_block = "\n".join(args.files)
    else:
        data_block = sys.stdin.read()

    script = render_download_script(data_block, username=args.user)
    sys.stdout.write(script)

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BrokenPipeError:
        try:
            sys.stdout.close()
        finally:
            raise SystemExit(0)


