"""Renders downloader shell script from a file list/table.

Reads FITS filenames from positional args or stdin.
Input may be a plain list or a table; in table mode only the first column
is used. The resulting script is written to stdout.

The downloader script is generated by `ocafitsfiles.render_download_script`.

v. 1.0.0
"""

import argparse
import logging
import signal
import sys
from argparse import ArgumentParser
from pathlib import Path
from typing import Iterable, List

from ocafitsfiles import render_download_script

log = logging.getLogger("collectdownloader")


def extract_filenames(lines: Iterable[str]) -> List[str]:
    """Extract FITS filenames from plain list/table lines.

    Rules:
    - blank lines are ignored
    - comment lines starting with '#' are ignored
    - first column is taken (`|` table separator first, whitespace fallback)
    - first column may be a path; only basename is kept
    """
    out: List[str] = []

    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        if "|" in line:
            first = line.split("|", 1)[0].strip()
        else:
            parts = line.split(None, 1)
            first = parts[0] if parts else ""

        if not first:
            continue

        if first.upper() in {"PATH", "NAME", "FILENAME", "FILE"}:
            continue

        out.append(Path(first).name)

    return out


def main() -> int:
    argparser = ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    argparser.add_argument(
        "files",
        nargs="*",
        help="Input rows (if omitted, read from stdin)",
    )
    argparser.add_argument(
        "-u",
        "--user",
        required=True,
        help="OCADB username embedded in generated downloader script",
    )
    argparser.add_argument("-v", "--verbose", action="count", default=0)

    argparser.epilog = """
examples:

    fitscollect -n -o ngc300 | fitscollectdownloader -u mkopernik > download.sh
    fitscollectparquet -n --sciprog FT2025B-1 | fitscollectdownloader -u mkopernik > download.sh
    fitscollectlist file1.fits file2.fits | fitscollectdownloader -u mkopernik > download.sh
    fitscollectdownloader -u mkopernik zb08c_1075_66218.fits zb08c_1075_66218_zdf.fits > download.sh
"""

    args = argparser.parse_args()

    try:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except (AttributeError, ValueError):
        pass

    log_format = "%(asctime)s [%(levelname)s] [%(name)s] %(message)s"
    if args.verbose == 1:
        logging.basicConfig(level=logging.INFO, format=log_format)
    elif args.verbose > 1:
        logging.basicConfig(level=logging.DEBUG, format=log_format)
    else:
        logging.basicConfig(level=logging.WARNING, format=log_format)

    source_lines = args.files if args.files else sys.stdin.readlines()
    filenames = extract_filenames(source_lines)

    if not filenames:
        log.warning("No filenames found in input")

    data_block = "\n".join(filenames)
    script = render_download_script(data_block, username=args.user)
    sys.stdout.write(script)

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BrokenPipeError:
        try:
            sys.stdout.close()
        finally:
            raise SystemExit(0)


